### ISSUE TITLE
Сделать верстку блоков связанных с видео (video, two-videos, three-videos)

### ISSUE THREAD

**Issue by MariaMantusova** [work-in-group/lubimovka#17]
- [Макет в фигма](https://www.figma.com/file/sPmrkcsXbuuHC24zIRktfJ/lubimovka-(pr.page)?node-id=1%3A348)
- Всю разработку вести в отдельной ветке, потом пул реквест делать в develop
- Привязать пул реквест с выполнением этой задачи, к этой задаче (сбоку есть Development, там выбрать ветку в которой велась разработка и добавить)

**Comment by apant94** [comment]
Пул реквест направила https://github.com/work-in-group/lubimovka/pull/23
