### ISSUE TITLE
Задача для Анны

### ISSUE THREAD

**Issue by MariaMantusova** [work-in-group/lubimovka#4]
В этой задачи тебе нужно:

1. Просмотреть мой пул реквест
2. Склонировать к себе этот репозиторий(ветку main, она пока без текста)
3. Создать свою ветку и в ней добавить свою строку
4. Запушить свою ветку и сделать пул реквест
5. Попробовать сделать апрув для какого-то из пул реквестов

**Comment by apant94** [comment]
сделано!
